services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81' # Panel de administración
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  pihole:
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Necesario para DHCP
      - "8080:80"   # Acceso web a Pi-hole en puerto 8080
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: 'hicken' # Cambia esto
      DNSMASQ_LISTENING: 'all'
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Requerido para funciones DHCP
